permalink: /:year/:month/:day/:title.html
gems: [jekyll-paginate]
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: wfwu
  email: wenfenwu@qq.com
  link: http://wfwu.github.io
#  weibo: http://weibo.com/dunyixu
  github: http://github.com/wfwu
#  twitter: https://twitter.com/dunyixu
# linkedin: 

# 站点信息
title: 会叫猫~的猫
description: My personal blog
url: http://wfwu.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/icon.png
favicon: /public/img/icon.png

# google analytics 设置
ga:
  id: UA-75069081-1
  url: wfwu.github.io

# disqus 设置
disqus:
  shortname: wfwu

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - 技术
  - 护肤

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
